"""Package the paper into a submission-ready zip.

The course requires a single .zip containing main.tex, refs.bib, figures, images,
and helper files. Source code itself goes on the GitHub repo cited inside the paper.

Output layout:
    fedsafe_fuse_submission/
        main.tex          (paths to figures rewritten to figures/...)
        refs.bib
        tables/*.tex
        figures/*.png     (only the ones actually used in the paper)
        README.txt        (build instructions, list of contents)

Run from anywhere:  python3 scripts/build_submission_zip.py
"""
from __future__ import annotations

import os
import re
import shutil
import zipfile
from pathlib import Path

REPO = Path("/Users/furkanyakkan/Documents/Image Fusion Final")
PAPER = REPO / "paper"
FIGURES = REPO / "figures"
STAGING = REPO / "submission_staging"
ZIP_OUT = REPO / "submission.zip"

# Figures actually used in the paper (re-derived from main.tex below as a check).
FIGS_USED = [
    "convergence_curves.png",
    "attack_reconstructions.png",
    "privacy_vs_comm.png",
    "uncertainty_heatmaps.png",
    "ablation_fipca_rank_v2.png",
]


def fresh_staging() -> None:
    if STAGING.exists():
        shutil.rmtree(STAGING)
    STAGING.mkdir()
    (STAGING / "tables").mkdir()
    (STAGING / "figures").mkdir()


def rewrite_main_tex() -> None:
    """Copy main.tex into staging, replacing `../figures/...` with `figures/...`."""
    src = (PAPER / "main.tex").read_text()
    rewritten = src.replace("../figures/", "figures/")
    (STAGING / "main.tex").write_text(rewritten)
    # Sanity check: confirm we didn't miss any figure paths
    bad = re.findall(r"\.\./figures/", rewritten)
    assert not bad, f"residual ../figures/ refs after rewrite: {bad}"


def copy_aux() -> None:
    # Bibliography
    shutil.copy(PAPER / "refs.bib", STAGING / "refs.bib")
    # Tables
    for t in (PAPER / "tables").glob("*.tex"):
        shutil.copy(t, STAGING / "tables" / t.name)
    # Figures (only used ones)
    for f in FIGS_USED:
        src = FIGURES / f
        assert src.exists(), f"missing figure {src}"
        shutil.copy(src, STAGING / "figures" / f)


def write_readme() -> None:
    readme = """\
FedSafe-Fuse — Submission Package
==================================

Author:  Furkan Yakkan
Course:  Advanced Applications & Performance Evaluation
Round:   Round 1 (deadline 2026-06-03)

Contents
--------
main.tex             — IEEE Conference Proceedings paper source
refs.bib             — BibTeX bibliography (14 verified entries)
tables/*.tex         — 4 result tables, auto-generated by scripts/build_paper_artifacts.py
                       (\\input{} into main.tex)
figures/*.png        — 5 publication figures
                         * convergence_curves.png     (Phase 3 federated convergence)
                         * attack_reconstructions.png (Phase 5 DLG outputs)
                         * privacy_vs_comm.png        (Phase 5 trade-off scatter)
                         * uncertainty_heatmaps.png   (Phase 4 SACP qualitative)
                         * ablation_fipca_rank_v2.png (Phase 6 rank ablation)

How to build the paper
----------------------
From inside the unzipped folder:

    pdflatex main.tex
    bibtex   main
    pdflatex main.tex
    pdflatex main.tex

Output:  main.pdf  (6 pages, IEEE conference format, A4)

Source code and reproduction notebooks
--------------------------------------
The full source code, trained Round-1 checkpoints, per-pixel SACP conformity
scores, and Colab notebooks that produced every figure and table are available
at the GitHub repository cited in the Acknowledgements section of the paper.
"""
    (STAGING / "README.txt").write_text(readme)


def zip_it() -> None:
    if ZIP_OUT.exists():
        ZIP_OUT.unlink()
    with zipfile.ZipFile(ZIP_OUT, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _, files in os.walk(STAGING):
            for name in files:
                full = Path(root) / name
                arc = full.relative_to(STAGING.parent)
                # Rename top-level "submission_staging" to "fedsafe_fuse_submission"
                arc_parts = list(arc.parts)
                arc_parts[0] = "fedsafe_fuse_submission"
                zf.write(full, str(Path(*arc_parts)))


def main() -> None:
    fresh_staging()
    rewrite_main_tex()
    copy_aux()
    write_readme()
    zip_it()
    size_kb = ZIP_OUT.stat().st_size / 1024
    print(f"Built {ZIP_OUT} ({size_kb:,.0f} KB)")
    with zipfile.ZipFile(ZIP_OUT) as zf:
        for n in zf.namelist():
            print(f"  {n}")


if __name__ == "__main__":
    main()
