"""Generate publication-ready LaTeX tables and a cleaner ablation figure from
the Round 1 CSVs. Run locally (no Colab, no GPU needed).

Inputs (already in results/):
    - round1_main.csv          (Phase 3: per-round federated training metrics)
    - coverage_table.csv       (Phase 4: SACP coverage table)
    - attack_table.csv         (Phase 5: DLG reconstruction MSE/SSIM/PSNR)
    - comm_cost_summary.csv    (Phase 5: bytes/round + compression)
    - ablation_fipca_rank.csv  (Phase 6: rank sweep)

Outputs:
    - paper/tables/main_results.tex
    - paper/tables/coverage.tex
    - paper/tables/attack.tex
    - paper/tables/ablation_rank.tex
    - figures/ablation_fipca_rank_v2.png  (re-rendered with sensible y-axis)
"""
from __future__ import annotations

import csv
import os
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

REPO = Path("/Users/furkanyakkan/Documents/Image Fusion Final")
RESULTS = REPO / "results"
TABLES = REPO / "paper" / "tables"
FIGURES = REPO / "figures"
TABLES.mkdir(parents=True, exist_ok=True)


def fmt_bytes(n: float) -> str:
    """Compact human-readable byte size for table cells (LaTeX-safe)."""
    n = float(n)
    if n >= 1e6:
        return f"{n / 1e6:.2f}\\,MB"
    if n >= 1e3:
        return f"{n / 1e3:.1f}\\,KB"
    return f"{int(n)}\\,B"


# ---------------------------------------------------------------------------
# Table 1 — Main federated training results (Phase 3)
# Method × Privacy × Final SSIM × Final PSNR × bytes/round
# ---------------------------------------------------------------------------
def build_main_results_table() -> str:
    df = pd.read_csv(RESULTS / "round1_main.csv")
    rows = []
    for tag, label, privacy in [
        ("ifcnn_fedavg", "FedAvg + IFCNN (B2)", "none"),
        ("fedsafe_dpsgd", "FedAvg + DP-SGD (B1)", "DP, $\\sigma\\!=\\!0.5$"),
        ("fedsafe_fipca", "FedSafe-Fuse + FIPCA (\\textbf{ours})", "rank-32 proj."),
    ]:
        sub = df[df["tag"] == tag]
        final = sub.dropna(subset=["eval_ssim"]).iloc[-1]
        bytes_pr = float(sub["bytes_per_round"].iloc[0])
        rows.append({
            "method": label,
            "privacy": privacy,
            "ssim": float(final["eval_ssim"]),
            "psnr": float(final["eval_psnr"]),
            "bytes": bytes_pr,
        })

    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Federated training results on MedMNIST OrganAMNIST "
        "(K=3 clients, T=50 rounds, E=5 local epochs, batch=16, "
        "40 samples/client/local-epoch; see Methods).}",
        "\\label{tab:main_results}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{lcccr}",
        "\\toprule",
        "Method & Privacy mechanism & SSIM~$\\uparrow$ & PSNR (dB)~$\\uparrow$ & Bytes per round~$\\downarrow$ \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r['method']} & {r['privacy']} & "
            f"{r['ssim']:.3f} & {r['psnr']:.2f} & {fmt_bytes(r['bytes'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 2 — SACP coverage table (Phase 4)
# ---------------------------------------------------------------------------
def build_coverage_table() -> str:
    df = pd.read_csv(RESULTS / "coverage_table.csv")
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Phase~4 SACP empirical coverage on MedMNIST test split. "
        "Calibrated on 5{,}184 held-out training samples; evaluated on 256 unseen "
        "test samples. All six empirical coverages meet or exceed their target.}",
        "\\label{tab:coverage}",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\begin{tabular}{cccccc}",
        "\\toprule",
        "$\\alpha$ & Target & Int.\\ cov.~$\\geq$ & Int.\\ width & Bnd.\\ cov.~$\\geq$ & Bnd.\\ width \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"{r['alpha']:.2f} & {r['target']:.2f} & "
            f"{r['interior_coverage']:.3f} & {r['interior_width']:.3f} & "
            f"{r['boundary_coverage']:.3f} & {r['boundary_width']:.3f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 3 — DLG attack reconstruction error (Phase 5)
# ---------------------------------------------------------------------------
def build_attack_table() -> str:
    df_atk = pd.read_csv(RESULTS / "attack_table.csv")
    df_comm = pd.read_csv(RESULTS / "comm_cost_summary.csv")
    bytes_lookup = {
        "raw":   df_comm.iloc[0]["bytes_per_round"],     # IFCNN's raw delta
        "dpsgd": df_comm.iloc[1]["bytes_per_round"],     # DP-SGD on FedSafe
        "fipca": df_comm.iloc[2]["bytes_per_round"],     # FIPCA on FedSafe
    }
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Phase~5 DLG gradient-inversion attack (Zhu \\textit{et al.\\/} 2019) on a 10\\,K-param surrogate. "
        "Lower reconstruction SSIM/PSNR means stronger privacy. "
        "FIPCA matches DP-SGD's privacy outcome at four orders of magnitude lower communication cost.}",
        "\\label{tab:attack}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{lcccr}",
        "\\toprule",
        "Protection & MSE & SSIM~$\\downarrow$ & PSNR (dB)~$\\downarrow$ & Bytes per round~$\\downarrow$ \\\\",
        "\\midrule",
    ]
    label_lookup = {
        "raw":   "None (raw gradients)",
        "dpsgd": "DP-SGD ($\\sigma\\!=\\!0.5$, $C\\!=\\!1.0$)",
        "fipca": "FIPCA (rank-32) [\\textbf{ours}]",
    }
    for _, r in df_atk.iterrows():
        tag = r["tag"]
        bytes_pr = bytes_lookup[tag]
        lines.append(
            f"{label_lookup[tag]} & "
            f"{r['mse']:.2e} & {r['ssim']:.4f} & {r['psnr_db']:.1f} & "
            f"{fmt_bytes(bytes_pr)} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table 4 — FIPCA rank ablation (Phase 6)
# ---------------------------------------------------------------------------
def build_ablation_table() -> str:
    df = pd.read_csv(RESULTS / "ablation_fipca_rank.csv")
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Phase~6 FIPCA rank ablation (K=3, T=25, E=5, 40 samples/client/local-epoch). "
        "Within the Round-1 training budget, rank effectively only controls communication cost; "
        "SSIM is flat across ranks because the model has not escaped its near-constant initialisation regime.}",
        "\\label{tab:ablation_rank}",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\begin{tabular}{ccccr}",
        "\\toprule",
        "Rank $d$ & SSIM & PSNR (dB) & Bytes/round & Compression vs DP-SGD \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"{int(r['rank'])} & {r['final_ssim']:.4f} & {r['final_psnr']:.2f} & "
            f"{int(r['bytes_per_round']):,} & {r['compression_vs_dpsgd']:,.0f}$\\times$ \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


# ===========================================================================
# ROUND-2 tables (BraTS real data, full-backbone DLG, leakage proxies, DP acct)
# ===========================================================================

# ---------------------------------------------------------------------------
# Table R2-1 — BraTS real multi-modal federated results (Phase 10B)
# ---------------------------------------------------------------------------
def build_brats_results_table() -> str:
    df = pd.read_csv(RESULTS / "brats_train.csv")
    rows = []
    for tag, label, privacy in [
        ("ifcnn_fedavg_brats", "FedAvg + IFCNN", "none"),
        ("fedsafe_fipca_brats", "FedSafe-Fuse + FIPCA (\\textbf{ours})", "rank-32 proj."),
    ]:
        sub = df[df["tag"] == tag]
        final = sub.dropna(subset=["eval_ssim"]).iloc[-1]
        rows.append({
            "method": label, "privacy": privacy,
            "ssim": float(final["eval_ssim"]), "psnr": float(final["eval_psnr"]),
            "bytes": float(sub["bytes_per_round"].iloc[0]),
        })
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Real multi-modal \\textbf{BraTS~2020} (T1/T2) federated results "
        "(K=3 HGG/LGG-skewed clients, 12 cases/client, T=50, E=5). IFCNN+FedAvg converges "
        "to high-fidelity fusion on real data; FIPCA holds the privacy/bandwidth operating point.}",
        "\\label{tab:brats_results}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{lccr}",
        "\\toprule",
        "Method & SSIM~$\\uparrow$ & PSNR (dB)~$\\uparrow$ & Bytes/round~$\\downarrow$ \\\\",
        "\\midrule",
    ]
    for r in rows:
        lines.append(
            f"{r['method']} & {r['ssim']:.3f} & {r['psnr']:.2f} & {fmt_bytes(r['bytes'])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table R2-2 — BraTS SACP coverage (Phase 10B)
# ---------------------------------------------------------------------------
def build_brats_coverage_table() -> str:
    df = pd.read_csv(RESULTS / "coverage_table_brats.csv")
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{SACP empirical coverage on \\textbf{real BraTS} data, calibrated and "
        "evaluated on disjoint held-out BraTS cases using the converged IFCNN model. "
        "All six coverages meet their target; with a well-trained model the boundary "
        "intervals are now \\emph{wider} than interior --- the clinically expected pattern.}",
        "\\label{tab:brats_coverage}",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\begin{tabular}{cccccc}",
        "\\toprule",
        "$\\alpha$ & Target & Int.\\ cov. & Int.\\ width & Bnd.\\ cov. & Bnd.\\ width \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"{r['alpha']:.2f} & {r['target']:.2f} & "
            f"{r['interior_coverage']:.3f} & {r['interior_width']:.4f} & "
            f"{r['boundary_coverage']:.3f} & {r['boundary_width']:.4f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table R2-3 — Formal (eps, delta)-DP accounting (Phase 10D)
# ---------------------------------------------------------------------------
def build_dp_accounting_table() -> str:
    df = pd.read_csv(RESULTS / "dp_accounting.csv")
    worst = df.loc[df["epsilon"].idxmax()]
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Formal R\\'enyi-DP accounting for the DP-SGD baseline "
        "($\\sigma\\!=\\!0.5$, $C\\!=\\!1.0$, 750 noisy steps/client, $\\delta\\!=\\!10^{-5}$). "
        "Heavy sub-sampling keeps $\\varepsilon$ bounded but weak; the worst-case client "
        f"attains $\\varepsilon\\!=\\!{worst['epsilon']:.1f}$.}}",
        "\\label{tab:dp_accounting}",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Client & $N$ (local) & $q\\!=\\!b/N$ & $\\varepsilon$ at $\\delta\\!=\\!10^{-5}$ \\\\",
        "\\midrule",
    ]
    for _, r in df.iterrows():
        lines.append(
            f"{r['client']} & {int(r['N']):,} & {r['q']:.4f} & {r['epsilon']:.1f} \\\\"
        )
    lines += [
        "\\midrule",
        f"\\textbf{{Worst case}} & {int(worst['N']):,} & {worst['q']:.4f} & "
        f"\\textbf{{{worst['epsilon']:.1f}}} \\\\",
        "\\bottomrule", "\\end{tabular}", "\\end{table}", "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Table R2-4 — DLG against the full 4.9M backbone + leakage proxies (Phase 10C)
# ---------------------------------------------------------------------------
def build_dlg_full_table() -> str:
    da = pd.read_csv(RESULTS / "dlg_full_backbone.csv")
    lp = pd.read_csv(RESULTS / "leakage_proxies.csv")
    # Average the two modalities for a compact per-protection reconstruction SSIM
    label_lookup = {
        "raw":   "None (raw gradients)",
        "dpsgd": "DP-SGD ($\\sigma\\!=\\!0.5$)",
        "fipca": "FIPCA (rank-32) [\\textbf{ours}]",
    }
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{DLG against the \\textbf{full 4.9\\,M-parameter} FedSafe-Fuse backbone "
        "(batch~1, real MedMNIST pair). Even raw gradients barely reconstruct the inputs "
        "(SSIM~$\\approx$~0.06 vs.~0.9999 on the surrogate), and protections rank below raw.}",
        "\\label{tab:dlg_full}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Protection & MRI SSIM~$\\downarrow$ & PET SSIM~$\\downarrow$ & Mean SSIM~$\\downarrow$ \\\\",
        "\\midrule",
    ]
    for tag in ["raw", "dpsgd", "fipca"]:
        sub = da[da["protection"] == tag]
        mri = float(sub[sub["modality"] == "mri"]["ssim"].iloc[0])
        pet = float(sub[sub["modality"] == "pet"]["ssim"].iloc[0])
        lines.append(
            f"{label_lookup[tag]} & {mri:.4f} & {pet:.4f} & {(mri + pet) / 2:.4f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


def build_leakage_proxies_table() -> str:
    lp = pd.read_csv(RESULTS / "leakage_proxies.csv")
    name_lookup = {"surrogate": "Surrogate", "full_backbone": "Full backbone"}
    lines = [
        "% Auto-generated by scripts/build_paper_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Gradient-leakage proxies justifying the surrogate quantitatively. "
        "Both the FIPCA captured-energy fraction and the DP-SGD gradient SNR \\emph{shrink} "
        "as the model grows, so the surrogate is a conservative (attacker-favourable) proxy: "
        "protection shown on it holds a fortiori on the deployed 4.9\\,M model.}",
        "\\label{tab:leakage_proxies}",
        "\\renewcommand{\\arraystretch}{1.1}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Model & $N$ params & FIPCA capt.\\ energy & DP-SGD grad.\\ SNR \\\\",
        "\\midrule",
    ]
    for _, r in lp.iterrows():
        lines.append(
            f"{name_lookup[r['model']]} & {int(r['n_params']):,} & "
            f"{r['fipca_captured_energy_frac']:.4f} & {r['dpsgd_grad_snr']:.5f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Figure — Cleaner version of the ablation plot
# ---------------------------------------------------------------------------
def rebuild_ablation_figure() -> None:
    df = pd.read_csv(RESULTS / "ablation_fipca_rank.csv")
    ranks = df["rank"].tolist()
    ssims = df["final_ssim"].tolist()
    bytes_pr = df["bytes_per_round"].tolist()

    fig, ax1 = plt.subplots(figsize=(8.5, 5))
    color_q = "#2ca02c"
    color_c = "#1f77b4"

    ax1.set_xlabel("FIPCA projection rank  $d$", fontsize=11)
    ax1.set_ylabel("Final-round eval SSIM", color=color_q, fontsize=11)
    ax1.plot(ranks, ssims, "o-", color=color_q, linewidth=2.5, markersize=11)
    ax1.set_ylim(0.0, 1.0)  # honest scale relative to the maximum possible SSIM
    ax1.set_xticks(ranks)
    ax1.tick_params(axis="y", labelcolor=color_q)
    ax1.grid(True, alpha=0.3)
    # Annotate the SSIM values
    for x, y in zip(ranks, ssims):
        ax1.annotate(f"{y:.3f}", (x, y), xytext=(8, 6), textcoords="offset points",
                     fontsize=9, color=color_q)
    # Reference: IFCNN final SSIM as the "non-private upper bound"
    ax1.axhline(0.972, color=color_q, linestyle=":", alpha=0.5)
    ax1.text(ranks[0], 0.98, "IFCNN+FedAvg (non-private upper bound, SSIM=0.972)",
             color=color_q, fontsize=9)

    ax2 = ax1.twinx()
    ax2.set_ylabel("Upstream bytes per round (log)", color=color_c, fontsize=11)
    ax2.plot(ranks, bytes_pr, "s--", color=color_c, linewidth=2.5, markersize=11)
    ax2.set_yscale("log")
    ax2.set_ylim(50, 1e8)
    ax2.tick_params(axis="y", labelcolor=color_c)
    for x, y in zip(ranks, bytes_pr):
        ax2.annotate(f"{int(y)} B", (x, y), xytext=(8, -14), textcoords="offset points",
                     fontsize=9, color=color_c)
    ax2.axhline(59_178_012, color="#ff7f0e", linestyle=":", alpha=0.6)
    ax2.text(ranks[-1], 59_178_012 * 1.4, "DP-SGD baseline (59 MB)", color="#ff7f0e",
             fontsize=9, ha="right")

    plt.title("FIPCA rank ablation: quality plateau vs upstream bandwidth", fontsize=12)
    fig.tight_layout()
    out = FIGURES / "ablation_fipca_rank_v2.png"
    plt.savefig(out, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"Rebuilt {out}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    outputs = {
        "main_results.tex":   build_main_results_table(),
        "coverage.tex":       build_coverage_table(),
        "attack.tex":         build_attack_table(),
        "ablation_rank.tex":  build_ablation_table(),
        # Round-2 additions
        "brats_results.tex":  build_brats_results_table(),
        "brats_coverage.tex": build_brats_coverage_table(),
        "dp_accounting.tex":  build_dp_accounting_table(),
        "dlg_full.tex":       build_dlg_full_table(),
        "leakage_proxies.tex": build_leakage_proxies_table(),
    }
    for name, body in outputs.items():
        path = TABLES / name
        path.write_text(body)
        n_rows = body.count("\\\\")
        print(f"Wrote {path}  ({len(body):,} chars, ~{n_rows} table rows)")

    rebuild_ablation_figure()
    print("\nAll Phase 7 artifacts generated.")


if __name__ == "__main__":
    main()
